<?php
/**
 * @file
 * Paragraphs jQuery UI Accordion hooks and common functions.
 */

/**
 * Implements hook_field_formatter_info().
 */
function paragraphs_jquery_ui_accordion2_field_formatter_info() {
  // Generate default array.
  $formatter_definition = array(
    'paragraphs_jquery_ui_accordion2' => array(
      'label' => t('Paragraphs jQuery UI Accordion 2'),
      'field types' => array('paragraphs'),
      'settings' => array(
        'title' => NULL,
        'title_column_wrapper' => array(
          'title_column_default' => NULL,
          'title_column' => NULL,
        ),
        'view_mode' => 'default',
        'autoscroll' => NULL,
        'startclosed' => NULL,
      ),
    ),
  );
  // If an icon font module is present, include the icon field setting.
  if (paragraphs_jquery_ui_accordion2_icon_module_check()) {
    $formatter_definition['paragraphs_jquery_ui_accordion2']['settings']['icon_field'] = NULL;
  }
  // Return the final array.
  return $formatter_definition;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function paragraphs_jquery_ui_accordion2_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  if (paragraphs_jquery_ui_accordion2_icon_module_check()) {
    $summary = t('Use field <strong>@title</strong> for title, <strong>@icon</strong> for icon and display format <strong>@view_mode</strong> for content in paragraphs, autoscroll <strong>@autoscroll</strong> and startclosed <strong>@startclosed</strong>',
      array(
        '@title' => $settings['title'],
        '@icon' => $settings['icon_field'],
        '@view_mode' => $settings['view_mode'],
        '@autoscroll' => $settings['autoscroll'] ? t('enabled') : t('disabled'),
        '@startclosed' => $settings['startclosed'] ? t('enabled') : t('disabled'),
      )
    );
  }
  else {
    $summary = t('Use field <strong>@title</strong> for title and display format <strong>@view_mode</strong> for content in paragraphs, autoscroll <strong>@autoscroll</strong> and startclosed <strong>@startclosed</strong>',
      array(
        '@title' => $settings['title'],
        '@view_mode' => $settings['view_mode'],
        '@autoscroll' => $settings['autoscroll'] ? t('enabled') : t('disabled'),
        '@startclosed' => $settings['startclosed'] ? t('enabled') : t('disabled'),
      )
    );
  }
  return $summary;
}

/**
 * Define field types that are unsuitable for the title field.
 */
function paragraphs_jquery_ui_accordion2_title_exclude_field_types() {
  $field_types = array(
    // Core field types.
    'text_with_summary',
    'text_long',
    'list_boolean',
    'datetime',
    'date',
    'datestamp',
    'file',
    'image',
    'email',
    'number_integer',
    'number_decimal',
    'number_float',
    'link_field',
    'entityreference',
    'taxonomy_term_reference',
    // Contrib field types.
    'blockreference',
    'paragraphs',
    'youtube',
    'repeating_date',
    'serial',
    'fivestar',
  );
  return $field_types;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function paragraphs_jquery_ui_accordion2_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();

  $display_mode_options = array();
  $paragraphs_fields = array();
  $paragraphs_fields[NULL] = t('- Select a field -');

  $title_excluded_field_types = paragraphs_jquery_ui_accordion2_title_exclude_field_types();
  $title_allowable_fields = field_read_fields();

  foreach ($title_allowable_fields as $field_name => $field_data) {
    if (in_array($field_data['type'], $title_excluded_field_types)) {
      unset($title_allowable_fields[$field_name]);
    }
  }

  // Check every paragraph type.
  $bundles = paragraphs_bundle_load();
  foreach ($bundles as $bundle) {
    // Get list of all paragraph fields to select the title field and icon from.
    $instances = field_info_instances('paragraphs_item', $bundle->bundle);
    foreach ($instances as $paragraphs_instance) {
      $paragraphs_fields[$paragraphs_instance['field_name']] = $paragraphs_instance['label'];
    }

    // Get list of all paragraph display modes.
    $entity_type = entity_get_info('paragraphs_item');
    foreach ($entity_type['view modes'] as $mode => $info) {
      $display_mode_options[$mode] = $info['label'];
    }
  }

  $element['field_machine_name'] = array(
    '#type' => 'value',
    '#value' => $field['field_name'],
  );

  $paragraphs_title_options = array_intersect_key($paragraphs_fields, $title_allowable_fields);
  $element['title'] = array(
    '#type' => 'select',
    '#title' => t('Paragraph title'),
    '#default_value' => $settings['title'],
    '#options' => $paragraphs_title_options,
    '#ajax' => array(
      'event' => 'change',
      'callback' => 'paragraphs_jquery_ui_accordion2_title_column_callback',
      'wrapper' => 'title-column-wrapper',
      'method' => 'replace',
      'effect' => 'fade',
    ),
  );

  // Define the options for the field columns if the title field does not use
  // the default of 'value'.
  $options = array('value' => 'Default');
  $title_field_name = $form_state['values']['fields'][$field['field_name']]['settings_edit_form']['settings']['title'] ?? $settings['title'];
  if ($title_field_name) {
    $options = paragraphs_jquery_ui_accordion2_get_field_columns($title_field_name);
  }
  else {
    $options = array('value' => 'Default');
  }
  // Check if the title column is the default so we can hide the title column
  // field.
  $title_column_default = (bool) (count($options) == 1 && array_key_exists('value', $options));

  // Wrap the title column in a wrapper so we can update the options and also
  // hide the field if the column is the default.
  $element['title_column_wrapper'] = array(
    '#type' => 'container',
    '#prefix' => '<div id="title-column-wrapper">',
    '#suffix' => '</div>',
  );

  $element['title_column_wrapper']['title_column_default'] = array(
    '#type' => 'hidden',
    '#value' => $title_column_default ? 1 : 0,
  );

  $element['title_column_wrapper']['title_column'] = array(
    '#type' => 'select',
    '#title' => t('Paragraph title column'),
    '#default_value' => $settings['title_column'] ?? 'value',
    '#options' => $options,
    '#states' => array(
      'visible' => array(
        ':input[name$="[title_column_wrapper][title_column_default]"]' => array('value' => 0),
      ),
    ),
  );

  if (paragraphs_jquery_ui_accordion2_icon_module_check()) {
    $element['icon_field'] = array(
      '#type' => 'select',
      '#title' => t('Icon (to prefix title)'),
      '#default_value' => $settings['icon_field'],
      '#options' => $paragraphs_fields,
    );
  }
  $element['view_mode'] = array(
    '#type' => 'select',
    '#title' => t('Paragraph content display mode'),
    '#default_value' => $settings['view_mode'],
    '#options' => $display_mode_options,
  );
  $element['autoscroll'] = array(
    '#type' => 'checkbox',
    '#title' => t('AutoScroll'),
    '#default_value' => isset($settings['autoscroll']) ? $settings['autoscroll'] : 0,
  );
  $element['startclosed'] = array(
    '#type' => 'checkbox',
    '#title' => t('Start Closed'),
    '#default_value' => isset($settings['startclosed']) ? $settings['startclosed'] : 0,
  );
  return $element;
}

/**
 * AJAX Callback for title columns.
 */
function paragraphs_jquery_ui_accordion2_title_column_callback($form, $form_state) {
  // Retrieve the dynamic field name.
  foreach ($form['fields'] as $field_name => $field_info) {
    if (isset($field_info['format']['settings_edit_form']['settings']['field_machine_name']) &&
        $field_info['format']['settings_edit_form']['settings']['field_machine_name']['#value'] === $field_name) {
      // Return the dependent field or field wrapper inside this fields
      // formatter settings.
      return $form['fields'][$field_name]['format']['settings_edit_form']['settings']['title_column_wrapper'];
    }
  }
}

/**
 * Helper to get columns for any title fields that don't use the value column.
 */
function paragraphs_jquery_ui_accordion2_get_field_columns($title_field_name) {
  $field_info = field_info_field($title_field_name);
  $field_uses_value = (bool) array_key_exists('value', $field_info['columns']);
  $options = array();
  if ($field_uses_value) {
    $options = array('value' => 'Default');
  }
  else {
    $columns = array_keys($field_info['columns']);
    foreach ($columns as $column) {
      $options[$column] = $column;
    }
  }
  return $options;
}

/**
 * Implements hook_field_formatter_view().
 */
function paragraphs_jquery_ui_accordion2_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  // Replicate two checks from paragraphs_field_formatter_view().
  // Prevent displaying useless markup if we don't have any values.
  if (empty($items)) {
    return $element;
  }

  // If we are dealing with an empty paragraphs field, render an insert point.
  if ($items[0]['value'] == 'scratch_paragraph') {
    if (!empty($instance['settings']['modal_admin'])) {
      $entity_ids = entity_extract_ids($entity_type, $entity);
    }
    return $element;
  }

  $settings = $display['settings'];
  // Get view mode from entity.
  $display_view_mode = empty($settings['view_mode']) ? 'default' : $settings['view_mode'];
  // Get view mode from field instance (if configured).
  $view_mode = empty($instance['display'][$display_view_mode]['settings']['view_mode']) ? $display_view_mode : $instance['display'][$display_view_mode]['settings']['view_mode'];
  $element['#theme_wrappers'] = array('paragraphs_items');
  $element['#attributes']['class'][] = backdrop_clean_css_identifier('paragraphs-items');
  $element['#attributes']['class'][] = backdrop_clean_css_identifier('paragraphs-items-view-mode-' . $view_mode);
  $element['#attributes']['class'][] = backdrop_clean_css_identifier('paragraphs-items-field-' . $instance['field_name']);
  $element['#paragraphs_items_view_mode'] = $view_mode;

  // Define the accordion.
  $entity_ids = entity_extract_ids($entity_type, $entity);
  $entity_id = $entity_ids[0];
  $accordion_id = 'accordion-' . $instance['field_name'] . '-' . $entity_id;
  $element[0]['#attached'] = array(
    'library' => array(
      array('system', 'ui.accordion'),
    ),
    'js' => array(
      array(
        'data' => backdrop_get_path('module', 'paragraphs_jquery_ui_accordion2') . '/js/paragraphs_jquery_ui_accordion2.js',
        'type' => 'file',
      ),
      array(
        'data' => array('paragraphs_jquery_ui_accordion2' => array(
          'ids' => array($entity_id => $accordion_id),
          'autoscroll' => isset($settings['autoscroll']) ? $settings['autoscroll'] : 0,
          'startclosed' => isset($settings['startclosed']) ? $settings['startclosed'] : 0,
        )),
        'type' => 'setting',
      ),
    ),
  );
  $element[0]['accordion'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'id' => $accordion_id,
      'class' => array('para-jq-acc'),
    ),
  );

  // Combine the title and paragraph display mode to generate each accordion.
  $title_column = $settings['title_column_wrapper']['title_column'] ?? 'value';
  foreach ($items as $delta => $item) {
    $paragraphs_ids[$delta] = $item['value'];
    if ($paragraph = paragraphs_field_get_entity($item)) {
      $paragraph->setHostEntity($entity_type, $entity, $langcode);
      if (entity_access('view', 'paragraphs_item', $paragraph)) {
        // Get the title field from the paragraph.
        $paragraph_title = field_get_items('paragraphs_item', $paragraph, $settings['title']);
        // Declare the paragraph icon string as blank in case Font Awesome not
        // installed.
        $paragraph_icon_string = '';
        // Check if icon font module exists and return setting if it does then
        // prepare the icon, if present.
        if (paragraphs_jquery_ui_accordion2_icon_module_check()) {
          // Get the icon field from the paragraph.
          $paragraph_icon = field_get_items('paragraphs_item', $paragraph, $settings['icon_field']);
          ($paragraph_icon) ? $paragraph_icon_string = '<i class="' . $paragraph_icon[0]['value'] . '">&zwnj;</i> ' : '';
        }
        // Get the paragraph using the defined display mode.
        $paragraph_content = $paragraph->view($view_mode, $langcode);
        // Use the title to generate a unique id for each accordion item.
        $paragraphs_unique_id = backdrop_html_id(strtolower($paragraph_title[0][$title_column]));
        // Insert the title, unique_id and content into the accordion item
        // structure.
        $element[0]['accordion'][] = array(
          'title' => array('#markup' => '<h3><a id="'
            . $paragraphs_unique_id
            . '" href="#'
            . $paragraphs_unique_id
            . '">'
            . $paragraph_icon_string
            . $paragraph_title[0][$title_column]
            . '</a></h3>'),
          'content' => $paragraph_content,
        );
      }
    }
  }
  return $element;
}

/**
 * Helper function to check if icon font is enabled.
 */
function paragraphs_jquery_ui_accordion2_icon_module_check() {
  return module_exists('font_awesome');
}
