<?php
/**
 * @file
 * Paragraphs jQuery UI Accordion hooks and common functions.
 */

/**
 * Implements hook_field_formatter_info().
 */
function paragraphs_jquery_ui_accordion2_field_formatter_info() {
  // Generate default array.
  $formatter_definition = array(
    'paragraphs_jquery_ui_accordion2' => array(
      'label' => t('Paragraphs jQuery UI Accordion 2'),
      'field types' => array('paragraphs'),
      'settings' => array(
        'title' => NULL,
        'title_column_wrapper' => array(
          'title_column_default' => NULL,
          'title_column' => NULL,
        ),
        'view_mode' => 'default',
        'autoscroll' => NULL,
        'startclosed' => NULL,
      ),
    ),
  );
  // If an icon font module is present, include the icon field setting.
  if (paragraphs_jquery_ui_accordion2_icon_module_check()) {
    $formatter_definition['paragraphs_jquery_ui_accordion2']['settings']['icon_field_type'] = 'none';
    $formatter_definition['paragraphs_jquery_ui_accordion2']['settings']['icon_field_wrapper']['icon_field'] = NULL;
  }
  // Return the final array.
  return $formatter_definition;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function paragraphs_jquery_ui_accordion2_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  if (paragraphs_jquery_ui_accordion2_icon_module_check()) {
    $summary = t('Use field <strong>@title</strong> for title, <strong>@icon</strong> for icon and display format <strong>@view_mode</strong> for content in paragraphs, autoscroll <strong>@autoscroll</strong> and startclosed <strong>@startclosed</strong>',
      array(
        '@title' => $settings['title'],
        '@icon' => $settings['icon_field_wrapper']['icon_field'],
        '@view_mode' => $settings['view_mode'],
        '@autoscroll' => $settings['autoscroll'] ? t('enabled') : t('disabled'),
        '@startclosed' => $settings['startclosed'] ? t('enabled') : t('disabled'),
      )
    );
  }
  else {
    $summary = t('Use field <strong>@title</strong> for title and display format <strong>@view_mode</strong> for content in paragraphs, autoscroll <strong>@autoscroll</strong> and startclosed <strong>@startclosed</strong>',
      array(
        '@title' => $settings['title'],
        '@view_mode' => $settings['view_mode'],
        '@autoscroll' => $settings['autoscroll'] ? t('enabled') : t('disabled'),
        '@startclosed' => $settings['startclosed'] ? t('enabled') : t('disabled'),
      )
    );
  }
  return $summary;
}

/**
 * Define field types that are unsuitable for the title field.
 */
function paragraphs_jquery_ui_accordion2_title_exclude_field_types() {
  $field_types = array(
    // Core field types.
    'text_with_summary',
    'text_long',
    'list_boolean',
    'datetime',
    'date',
    'datestamp',
    'file',
    'image',
    'email',
    'number_integer',
    'number_decimal',
    'number_float',
    'link_field',
    'entityreference',
    'taxonomy_term_reference',
    // Contrib field types.
    'blockreference',
    'paragraphs',
    'youtube',
    'repeating_date',
    'serial',
    'fivestar',
    'icon',
  );
  return $field_types;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function paragraphs_jquery_ui_accordion2_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();

  $display_mode_options = array();
  $paragraphs_fields = array();
  $paragraphs_fields[NULL] = t('- Select a field -');

  $title_excluded_field_types = paragraphs_jquery_ui_accordion2_title_exclude_field_types();
  $title_allowable_fields = field_read_fields();

  foreach ($title_allowable_fields as $field_name => $field_data) {
    if (in_array($field_data['type'], $title_excluded_field_types)) {
      unset($title_allowable_fields[$field_name]);
    }
  }

  // Check every paragraph type.
  $bundles = paragraphs_bundle_load();
  foreach ($bundles as $bundle) {
    // Get list of all paragraph fields to select the title field and icon from.
    $instances = field_info_instances('paragraphs_item', $bundle->bundle);
    foreach ($instances as $paragraphs_instance) {
      $paragraphs_fields[$paragraphs_instance['field_name']] = $paragraphs_instance['label'];
    }

    // Get list of all paragraph display modes.
    $entity_type = entity_get_info('paragraphs_item');
    foreach ($entity_type['view modes'] as $mode => $info) {
      $display_mode_options[$mode] = $info['label'];
    }
  }

  $element['field_machine_name'] = array(
    '#type' => 'value',
    '#value' => $field['field_name'],
  );

  $paragraphs_title_options = array_intersect_key($paragraphs_fields, $title_allowable_fields);
  $element['title'] = array(
    '#type' => 'select',
    '#title' => t('Paragraph title'),
    '#default_value' => $settings['title'],
    '#options' => $paragraphs_title_options,
    '#ajax' => array(
      'event' => 'change',
      'callback' => 'paragraphs_jquery_ui_accordion2_title_column_callback',
      'wrapper' => 'title-column-wrapper',
      'method' => 'replace',
      'effect' => 'fade',
    ),
  );

  // Define the options for the field columns if the title field does not use
  // the default of 'value'.
  $options = array('value' => 'Default');
  $title_field_name = $form_state['values']['fields'][$field['field_name']]['settings_edit_form']['settings']['title'] ?? $settings['title'];
  if ($title_field_name) {
    $options = paragraphs_jquery_ui_accordion2_get_field_columns($title_field_name);
  }
  else {
    $options = array('value' => 'Default');
  }
  // Check if the title column is the default so we can hide the title column
  // field.
  $title_column_default = (bool) (count($options) == 1 && array_key_exists('value', $options));

  // Wrap the title column in a wrapper so we can update the options and also
  // hide the field if the column is the default.
  $element['title_column_wrapper'] = array(
    '#type' => 'container',
    '#prefix' => '<div id="title-column-wrapper">',
    '#suffix' => '</div>',
  );

  $element['title_column_wrapper']['title_column_default'] = array(
    '#type' => 'hidden',
    '#value' => $title_column_default ? 1 : 0,
  );

  $element['title_column_wrapper']['title_column'] = array(
    '#type' => 'select',
    '#title' => t('Paragraph title column'),
    '#default_value' => $settings['title_column'] ?? 'value',
    '#options' => $options,
    '#states' => array(
      'visible' => array(
        ':input[name$="[title_column_wrapper][title_column_default]"]' => array('value' => 0),
      ),
    ),
  );

  // Check for any icon modules.
  $icon_modules = paragraphs_jquery_ui_accordion2_icon_module_check();
  if ($icon_modules) {
    // If one or more icon modules is enabled, show the icon type setting.
    $icon_field_type_options = array(
      'none' => t('No icon'),
    );
    // Font Awesome.
    if (in_array('font_awesome', $icon_modules)) {
      $icon_field_type_options['font_awesome'] = t('Font Awesome text definition');
    }
    // Icon Field.
    if (in_array('iconfield', $icon_modules)) {
      $icon_field_type_options['iconfield'] = t('Icon Field');
    }
    $element['icon_field_type'] = array(
      '#type' => 'radios',
      '#title' => t('Icon Type'),
      '#default_value' => $settings['icon_field_type'],
      '#options' => $icon_field_type_options,
      '#ajax' => array(
        'event' => 'change',
        'callback' => 'paragraphs_jquery_ui_accordion2_icon_field_callback',
        'wrapper' => 'icon-field-wrapper',
        'method' => 'replace',
        'effect' => 'fade',
      ),
    );
    // Add additional description for the Font Awesome option.
    $fa_description = t('This option provides backwards compatibility with all previously defined paragraph fields using this module with Font Awesome icons. Going forward, using the Icon Field module to browse and select icons provides a much better editor experience.');
    $element['icon_field_type']['font_awesome']['#description'] = $fa_description;

    // If the Icon Field Type settings is populated retreive it from the
    // $form_state array.
    $icon_field_type = $form_state['values']['fields'][$field['field_name']]['settings_edit_form']['settings']['icon_field_type'] ?? $settings['icon_field_type'];

    // Populate the list of fields to select from depending on the Icon Field
    // Type selected.
    $paragraphs_icon_fields = array();
    switch ($icon_field_type) {
      case 'font_awesome':
        $field_types = array('text', 'list_text');
        $icon_allowable_fields = array();
        foreach ($field_types as $field_type) {
          $icon_allowable_fields = array_merge($icon_allowable_fields, field_read_fields(array('type' => $field_type)));
        }
        $paragraphs_icon_fields = array_intersect_key($paragraphs_fields, $icon_allowable_fields);
        break;
      case 'iconfield':
        $icon_allowable_fields = field_read_fields(array('type' => 'icon'));
        $paragraphs_icon_fields = array_intersect_key($paragraphs_fields, $icon_allowable_fields);
        break;
      default:
        $paragraphs_icon_fields['na'] = t('Not applicable');
    }
    if (empty($paragraphs_icon_fields)) {
      $paragraphs_icon_fields[0] = t('No fields available');
    }
    // Wrap the field in a wrapper so it can be updated via AJAX.
    $element['icon_field_wrapper'] = array(
      '#type' => 'container',
      '#prefix' => '<div id="icon-field-wrapper">',
      '#suffix' => '</div>',
      '#states' => array(
      ),
    );
    // Add and populate a hidden value so can hide or show the icon field.
    $icon_field_show = $icon_field_type != 'none';
    $element['icon_field_wrapper']['icon_field_show'] = array(
      '#type' => 'hidden',
      '#value' => $icon_field_show ? 1 : 0,
    );
    $element['icon_field_wrapper']['icon_field'] = array(
      '#type' => 'select',
      '#title' => t('Icon Field'),
      '#default_value' => $settings['icon_field_wrapper']['icon_field'] ?? 'na',
      '#options' => $paragraphs_icon_fields,
      '#states' => array(
        'visible' => array(
          ':input[name$="[icon_field_wrapper][icon_field_show]"]' => array('value' => 1),
        ),
        'required' => array(
          ':input[name$="[icon_field_wrapper][icon_field_show]"]' => array('value' => 1),
        ),
      ),
    );
  }
  // Select the Display View mode to show as the accordion content.
  $element['view_mode'] = array(
    '#type' => 'select',
    '#title' => t('Paragraph content display mode'),
    '#default_value' => $settings['view_mode'],
    '#options' => $display_mode_options,
  );

  // Accordion behaviour settings.
  $element['autoscroll'] = array(
    '#type' => 'checkbox',
    '#title' => t('AutoScroll'),
    '#default_value' => isset($settings['autoscroll']) ? $settings['autoscroll'] : 0,
  );
  $element['startclosed'] = array(
    '#type' => 'checkbox',
    '#title' => t('Start Closed'),
    '#default_value' => isset($settings['startclosed']) ? $settings['startclosed'] : 0,
  );
  return $element;
}

/**
 * AJAX Callback for title columns.
 */
function paragraphs_jquery_ui_accordion2_title_column_callback($form, $form_state) {
  // Retrieve the dynamic field name.
  foreach ($form['fields'] as $field_name => $field_info) {
    if (isset($field_info['format']['settings_edit_form']['settings']['field_machine_name']) &&
        $field_info['format']['settings_edit_form']['settings']['field_machine_name']['#value'] === $field_name) {
      // Return the dependent field or field wrapper inside this fields
      // formatter settings.
      return $form['fields'][$field_name]['format']['settings_edit_form']['settings']['title_column_wrapper'];
    }
  }
}

/**
 * AJAX Callback for icon fields.
 */
function paragraphs_jquery_ui_accordion2_icon_field_callback($form, $form_state) {
  // Retrieve the dynamic field name.
  foreach ($form['fields'] as $field_name => $field_info) {
    if (isset($field_info['format']['settings_edit_form']['settings']['field_machine_name']) &&
        $field_info['format']['settings_edit_form']['settings']['field_machine_name']['#value'] === $field_name) {
      // Return the dependent field or field wrapper inside this fields
      // formatter settings.
      return $form['fields'][$field_name]['format']['settings_edit_form']['settings']['icon_field_wrapper'];
    }
  }
}

/**
 * Helper to get columns for any title fields that don't use the value column.
 */
function paragraphs_jquery_ui_accordion2_get_field_columns($title_field_name) {
  $field_info = field_info_field($title_field_name);
  $field_uses_value = (bool) array_key_exists('value', $field_info['columns']);
  $options = array();
  if ($field_uses_value) {
    $options = array('value' => 'Default');
  }
  else {
    $columns = array_keys($field_info['columns']);
    foreach ($columns as $column) {
      $options[$column] = $column;
    }
  }
  return $options;
}

/**
 * Implements hook_field_formatter_view().
 */
function paragraphs_jquery_ui_accordion2_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  // Replicate two checks from paragraphs_field_formatter_view().
  // Prevent displaying useless markup if we don't have any values.
  if (empty($items)) {
    return $element;
  }

  // If we are dealing with an empty paragraphs field, render an insert point.
  if ($items[0]['value'] == 'scratch_paragraph') {
    if (!empty($instance['settings']['modal_admin'])) {
      $entity_ids = entity_extract_ids($entity_type, $entity);
    }
    return $element;
  }

  $settings = $display['settings'];
  // Get view mode from entity.
  $display_view_mode = empty($settings['view_mode']) ? 'default' : $settings['view_mode'];
  // Get view mode from field instance (if configured).
  $view_mode = empty($instance['display'][$display_view_mode]['settings']['view_mode']) ? $display_view_mode : $instance['display'][$display_view_mode]['settings']['view_mode'];
  $element['#theme_wrappers'] = array('paragraphs_items');
  $element['#attributes']['class'][] = backdrop_clean_css_identifier('paragraphs-items');
  $element['#attributes']['class'][] = backdrop_clean_css_identifier('paragraphs-items-view-mode-' . $view_mode);
  $element['#attributes']['class'][] = backdrop_clean_css_identifier('paragraphs-items-field-' . $instance['field_name']);
  $element['#paragraphs_items_view_mode'] = $view_mode;

  // Define the accordion.
  $entity_ids = entity_extract_ids($entity_type, $entity);
  $entity_id = $entity_ids[0];
  $accordion_id = 'accordion-' . $instance['field_name'] . '-' . $entity_id;
  $element[0]['#attached'] = array(
    'library' => array(
      array('system', 'ui.accordion'),
    ),
    'js' => array(
      array(
        'data' => backdrop_get_path('module', 'paragraphs_jquery_ui_accordion2') . '/js/paragraphs_jquery_ui_accordion2.js',
        'type' => 'file',
      ),
      array(
        'data' => array('paragraphs_jquery_ui_accordion2' => array(
          'ids' => array($entity_id => $accordion_id),
          'autoscroll' => isset($settings['autoscroll']) ? $settings['autoscroll'] : 0,
          'startclosed' => isset($settings['startclosed']) ? $settings['startclosed'] : 0,
        )),
        'type' => 'setting',
      ),
    ),
    'css' => array(
      backdrop_get_path('module', 'paragraphs_jquery_ui_accordion2') . '/css/paragraphs_jquery_ui_accordion2.css',
    ),
  );
  $element[0]['accordion'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'id' => $accordion_id,
      'class' => array('para-jq-acc'),
    ),
  );

  // Combine the title and paragraph display mode to generate each accordion.
  $title_column = $settings['title_column_wrapper']['title_column'] ?? 'value';
  foreach ($items as $delta => $item) {
    $paragraphs_ids[$delta] = $item['value'];
    if ($paragraph = paragraphs_field_get_entity($item)) {
      $paragraph->setHostEntity($entity_type, $entity, $langcode);
      if (entity_access('view', 'paragraphs_item', $paragraph)) {
        // Get the title field from the paragraph.
        $paragraph_title_field = field_get_items('paragraphs_item', $paragraph, $settings['title']);
        $paragraph_title = $paragraph_title_field[0][$title_column] ?? '';
        // Declare the paragraph icon string as blank in case Font Awesome not
        // installed.
        $paragraph_icon_string = '';
        // Check if icon font module exists and return setting if it does then
        // prepare the icon, if present.
        // @todo - UPDATE THIS SECTION
        $icon_field_type = $settings['icon_field_type'];
        if ($icon_field_type !== 'none') {
          // Get the icon field from the paragraph.
          $paragraph_icon = field_get_items('paragraphs_item', $paragraph, $settings['icon_field_wrapper']['icon_field']);

          // Format the icon according to the type of field.
          switch ($icon_field_type) {
            case 'font_awesome':
              ($paragraph_icon) ? $paragraph_icon_string = '<i class="' . $paragraph_icon[0]['value'] . '">&zwnj;</i> ' : '';
              break;
            case 'iconfield':
              ($paragraph_icon) ? $paragraph_icon_string = icon($paragraph_icon[0]['key']) . ' ' : '';
          }
        }
        // Get the paragraph using the defined display mode.
        $paragraph_content = $paragraph->view($view_mode, $langcode);
        // Use the title to generate a unique id for each accordion item.
        $paragraphs_unique_id = backdrop_html_id(strtolower($paragraph_title));
        // Insert the title, unique_id and content into the accordion item
        // structure.
        $element[0]['accordion'][] = array(
          'title' => array('#markup' => '<h3><a id="'
            . $paragraphs_unique_id
            . '" href="#'
            . $paragraphs_unique_id
            . '">'
            . $paragraph_icon_string
            . $paragraph_title
            . '</a></h3>'),
          'content' => $paragraph_content,
        );
      }
    }
  }
  return $element;
}

/**
 * Helper function to check if icon font is enabled.
 *
 * @return array|FALSE
 *   Return an array of module names or FALSE if none.
 */
function paragraphs_jquery_ui_accordion2_icon_module_check() {
  $result = array();
  $icon_modules = array(
    'font_awesome',
    'iconfield',
  );
  foreach ($icon_modules as $icon_module) {
    if (module_exists($icon_module)) {
      $result[] = $icon_module;
    }
  }
  return empty($result) ? FALSE : $result;
}
